ip_20200844/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from rest_framework import routers
#from blog import views

# = routers.DefaultRouter()
#router.register(r'tests', views.postViewSet)

urlpatterns = [ #IP주소
    path('admin/', admin.site.urls), #IP주소/admin/
    path('shop/', include('shop.urls')),
    path('', include('single_pages.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls'))
    #FBV스타일post_list 페이지만들기>url들>blog views
    #path('drf/', include(router.urls))

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from. import views

urlpatterns=[#IP주소/blog/
    path('post_list/',views.PostList.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('<int:pk>/', views.PostDetail.as_view(), name="post_detail"),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('category/<str:slug1>/', views.category_page),
    path('company/<str:slug>/', views.company_page),#IP주소/blog/category/slug
    path('tag/<str:slug>/', views.tag_page),
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('scrap/<int:pk>/', views.scrap, name="scrap")

    #path('', views.index), #IP주소/blog/
    #path('<int:pk:/', views.single_post_page)
    #blog/views변경
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shop/tag/{self.slug}/'


#다대일 관계
class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug1 = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shop/category/{self.slug1}/'

    class Meta:
        verbose_name_plural = 'Categories'


#다대일 관계
class Company(models.Model):
    #제조사명
    name = models.CharField(max_length=50, unique=True)
    #주소
    address = models.TextField()
    #연락처
    phone = models.CharField(max_length=11, unique=True)
    #이메일(추가 필드)
    email = models.TextField(max_length=254, unique=True)

    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/shop/company/{self.slug}/'

    class Meta:
        verbose_name_plural = 'Companies'


class Post(models.Model):
    #상품명
    title = models.CharField(max_length=30)
    #간단한 설명
    hook_text = models.CharField(max_length=100, blank=True)
    #content = models.TextField()
    content = MarkdownxField()
    #상품 이미지
    image = models.ImageField(upload_to='shop/images/%Y/%m/%d/', blank=True)
    #상품 가격
    price = models.IntegerField()
    #그 외의 필드(상품코드)
    product_code = models.CharField(max_length=30, blank=True)
    #제조사 포함
    company = models.ForeignKey(Company, null=True, blank=True, on_delete=models.SET_NULL)
    #Category 포함
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)
    #다대다 관계 필드 포함
    tags = models.ManyToManyField(Tag, blank=True)
    scrap = models.ManyToManyField(User, blank=True, related_name='scrap_name')

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def get_absolute_url(self):
        return f'/shop/{self.pk}/'

    def get_avatar_url(self):
         if self.author.socialaccount_set.exists():
             return self.author.socialaccount_set.first().get_avatar_url()
         else:
             return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'

    def get_content_markdown(self):
        return markdown(self.content)


class Comment(models.Model):
        post = models.ForeignKey(Post, on_delete=models.CASCADE)
        author = models.ForeignKey(User, on_delete=models.CASCADE)
        content = models.TextField()
        created_at = models.DateTimeField(auto_now_add=True)
        modified_at = models.DateTimeField(auto_now=True)

        def __str__(self):
            return f'{self.author}:{self.content}'

        def get_absolute_url(self):
            return f'{self.post.get_absolute_url()}#comment--{self.pk}'

        def get_avatar_url(self):
            if self.author.socialaccount_set.exists():
                return self.author.socialaccount_set.first().get_avatar_url()
            else:
                return 'https://dummyimage.com/50x50/ced4da/6c757d.jpg'


# class reComment(models.Model):
#     comment=models.ForeignKey(Comment,on_delete=models.CASCADE)
#     body=models.CharField('대댓글',max_length=150)
#     updated_at = models.DateTimeField(auto_now=True)
#
#     def __str__(self):
#         return self.body
#
#
# class ReCommentForm(forms.ModelForm):
#
#     class Meta:
#         model=reComment
#         fields=('body','comment')

shop/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            "content": forms.Textarea(attrs={
                'placeholder': '댓글을 작성해주세요',
                'class': 'form-control', 'rows': '3'
            })
        }

shop/views.py
from django.shortcuts import render, redirect
from .models import Post, Category, Company, Tag, Comment
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q



class PostUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'image', 'price', 'product_code', 'company', 'category']
    template_name = 'shop/post_update_form.html'

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tags.exists:
            tag_str_list = list()
            for t in self.object.tags.all():
                tag_str_list.append(t.name)
            context['tags_str_default'] = ','.join(tag_str_list)
        context['categories'] = Category.objects.all
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        context['companies'] = Company.objects.all
        context['no_company_post_count'] = Post.objects.filter(company=None).count
        return context

    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tags.clear()
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(';', ',')
            #;는 ,로 바꿔줌
            tag_list = tags_str.split(',')
            for t in tag_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response


class PostCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    fields = ['title', 'hook_text', 'content', 'image', 'price', 'price', 'product_code', 'company', 'category']
    #tags 넣으면 사용자가 적는 tags가 아닌 선택하는 tags가 나타남
    #모델명_form.html이라는 템플릿 자동 호출

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_superuser or current_user.is_staff):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                tags_str = tags_str.replace(';', ',')
                #;는 ,로 바꿔줌
                tag_list = tags_str.split(',')
                for t in tag_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
            return response
        else:
            return redirect('/shop/')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostCreate, self).get_context_data()
        context['categories'] = Category.objects.all
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        context['companies'] = Company.objects.all
        context['no_company_post_count'] = Post.objects.filter(company=None).count
        return context


class PostList(ListView):
    model = Post
    ordering = '-pk'
    paginate_by= 9
    #>>cbv 페이지

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostList, self).get_context_data()
        context['categories'] = Category.objects.all
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        context['companies'] = Company.objects.all
        context['no_company_post_count'] = Post.objects.filter(company=None).count
        return context
    #템플릿은 모델명_list.html : post_list.html
    #매개변수 모델명_list : post_list라는 데이터 전달


class PostSearch(PostList):
    # ListView를 상속받음, post_list, post_list.html
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(Q(title__contains=q) | Q(tags__name__contains=q)).distinct()
        return post_list

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        return context


class PostDetail(DetailView):
    model = Post
    #cbv

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all
        context['no_category_post_count'] = Post.objects.filter(category=None).count
        context['companies'] = Company.objects.all
        context['no_company_post_count'] = Post.objects.filter(company=None).count
        context['comment_form'] = CommentForm
        return context


    #템플릿은 모델명_detail.html : post_detail.html
    #매개변수 모델명: post

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:  # POST아닌 GET일 떄
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied


def delete_comment(request, pk):
        comment = get_object_or_404(Comment, pk=pk)
        if request.user.is_authenticated and request.user == comment.author:
            comment.delete()
            return redirect(comment.get_absolute_url())
        else:
            PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    # comment_form
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


def scrap(request, pk):
    post = get_object_or_404(Post, pk=pk) # pk값에 해당하는 게시물 받아옴
    user = request.user
    if user in post.scrap.all(): # 요청 유저가 이미 스크랩을 했으면
        post.scrap.remove(user) # 유저 삭제
    else: # 스크랩을 아직 안한 유저라면
        post.scrap.add(user) # 스크랩 목록에 요청 유저 추가
    return redirect('post_detail', pk)

def scrap_list(request):
    user = request.user
    return render(request, 'mypage.html', {'user':user})



def category_page(request, slug1):
    if slug1 == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug1=slug1)
        post_list = Post.objects.filter(category=category)
    return render(request, 'shop/post_list.html', {
                    'category': category,
                    'post_list': post_list,
                    'categories': Category.objects.all(),
                    'no_category_post_count': Post.objects.filter(category=None).count,
                    'companies': Company.objects.all(),
                    'no_company_post_count': Post.objects.filter(company=None).count
    })


def company_page(request, slug):
    if slug == 'no_company':
        company = '미분류'
        post_list = Post.objects.filter(company=None)
    else:
        company = Company.objects.get(slug=slug)
        post_list = Post.objects.filter(company=company)
    return render(request, 'shop/post_list.html', {
                    'company': company,
                    'post_list': post_list,
                    'companies': Company.objects.all(),
                    'no_company_post_count': Post.objects.filter(company=None).count,
                    'categories': Category.objects.all(),
                    'no_category_post_count': Post.objects.filter(category=None).count
    })


def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()
    return render(request, 'shop/post_list.html', {
        'tag': tag,
        'post_list': post_list,
        'categories': Category.objects.all(),
        'no_category_post_count': Post.objects.filter(category=None).count,
        'companies': Company.objects.all(),
        'no_company_post_count': Post.objects.filter(company=None).count
    })


#query로 post목록 가져오기
#def index(request):
    #posts=Post.objects.all().order_by('pk')
    #return render(request, 'blog\index.html', {'posts':posts})

#def single_post_page(request,pk):
    #post = Post.objects.get(pk=pk)
    #return render(request,'blog/single_post_page.html',{'post':post})

shop/templates/shop/comment_form.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>COZY FUZZY | 댓글수정 </title>
  <link href="{% static 'single_pages/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen">
    <link href="{% static 'single_pages/css/customstyles.css' %}" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/3385a22710.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap" rel="stylesheet">
<!-- Footer-->

</head>
<body>
{% include 'shop/navbar.html' %}

<style>
    *{
        font-family: 'Noto Sans KR', sans-serif;
    }

</style>

{% include 'shop/flow.html' %}

{% load crispy_forms_tags %}

    <div class="container align-self-center" style="background-color:white">
        <h1>Edit Comment</h1>
            <hr/>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                    {{form | crispy}}
                <button type="submit" class="btn btn-primary float-right" style="background-color:#5Dbb63">Submit</button><br><br>
            </form>
        </div>

    {% include 'shop/flow.html' %}
    {% include 'shop/footer.html' %}

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/flow.html
<div class="flow-container" id="floating">
        <div class="flow-text">
            <div class="flow-wrap">BRING HOME A COZY FRIEND •°</div>
            <div class="flow-wrap">포근한 친구를 집으로 데려오세요 •°</div>
            <div class="flow-wrap">BRING HOME A COZY FRIEND •°</div>
            <div class="flow-wrap">포근한 친구를 집으로 데려오세요 •°</div>
            <div class="flow-wrap">BRING HOME A COZY FRIEND •°</div>
            <div class="flow-wrap">포근한 친구를 집으로 데려오세요 •°</div>
            <div class="flow-wrap">BRING HOME A COZY FRIEND •°</div>
            <div class="flow-wrap">포근한 친구를 집으로 데려오세요 •°</div>
            <div class="flow-wrap">BRING HOME A COZY FRIEND •°</div>
            <div class="flow-wrap">포근한 친구를 집으로 데려오세요 •°</div>
            <div class="flow-wrap">BRING HOME A COZY FRIEND •°</div>
            <div class="flow-wrap">포근한 친구를 집으로 데려오세요 •°</div>
            <div class="flow-wrap">BRING HOME A COZY FRIEND •°</div>
            <div class="flow-wrap">포근한 친구를 집으로 데려오세요 •°</div>
        </div>
</div>

shop/templates/shop/footer.html
<footer class="py-4" style="background-color:#fff">
            <br>
            <div class="container">
                <div class="row">
                    <span class="col-3">
                        <span class="footer-image"><img src="/static/single_pages/css/title.png"></span>
                    </span>
                    <br>
                    <span class="col-6">
                        <h6 style="font-size:0.86rem; line-height: 1.4">
                            ㈜코지퍼지<br>
                            대표이사: 이동희/서울특별시 도봉구 삼양로 144길 33 덕성여자대학교 차미리사관 229호<br>
                            사업자등록번호: 211-87-00620 / 통신판매업 신고: 제 01-1968호<br>
                            개인정보보호책임자: 이동희 / 소비자피해보상보험 SGI 서울보증<br><br>

                            호스팅서비스:㈜코지퍼지<br>
                            COPYRIGHT © COZYFUZZY ALL RIGHTS RESERVED.<br>
                        </h6>
                    </span>
                    <br>
                    <div class="card col-3 border-0" style="width: 14rem; height: 8rem; background-color:#e9efea">
                        <div class="card-body" style="padding-left:0.5rem;">
                            <h5 class="card-title" style="font-size:0.86rem; font-weight: bold">
                                고객센터 문의
                            </h5>
                            <h6 class="card-text mb-2" style="font-size:0.76rem">
                                운영시간: 10시 ~ 17시 (주말, 공휴일 휴무)
                            </h6>
                            <h6 class="card-text mb-2" style="font-size:0.76rem">
                                전화번호: 02-901-8341
                            </h6>
                            <br>
                        </div>

                    </div>
                </div>
            </div>
        </footer>

shop/templates/shop/post_form.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>COZY FUZZY | 상품등록 </title>
  <link href="{% static 'single_pages/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen">
    <link href="{% static 'single_pages/css/customstyles.css' %}" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/3385a22710.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap" rel="stylesheet">
<!-- Footer-->

</head>
<body>
{% include 'shop/navbar.html' %}

<style>
    *{
        font-family: 'Noto Sans KR', sans-serif;
    }

</style>
{% include 'shop/flow.html' %}

{% load crispy_forms_tags %}

    <div class="container align-self-center" style="background-color:white">
        <h1>상품 등록</h1>
        <hr/>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

                {{ form | crispy }}

                 <div id="div_id_tags_str">
                     <label for="id_tags">Tags:</label>
                     <input id="id_tags" type="text" name="tags_str" class="textinput textInput form-control">
                </div>
            <br>
            <button type="submit " class="btn btn-primary btn-block" style="background-color:#5Dbb63">Submit</button><br>
        </form>
        {{form.media}}
    </div>

    {% include 'shop/flow.html' %}
    {% include 'shop/footer.html' %}

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/post_update_form.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>COZY FUZZY | 상품수정 </title>
  <link href="{% static 'single_pages/bootstrap4/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen">
    <link href="{% static 'single_pages/css/customstyles.css' %}" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/3385a22710.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap" rel="stylesheet">
<!-- Footer-->

</head>
<body>
{% include 'shop/navbar.html' %}

<style>
    *{
        font-family: 'Noto Sans KR', sans-serif;
    }

</style>
{% include 'shop/flow.html' %}

{% load crispy_forms_tags %}

    <div class="container align-self-center" style="background-color:white">
        <h1>상품 수정</h1>
        <hr/>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
                {{form | crispy}}
                   <div id="div_id_tags_str">
                    <label for="id_tags">Tags:</label>
                    <input id="id_tags" type="text" name="tags_str" value="{{tags_str_default}}" class="textinput textInput form-control">
                   </div>
            <br>
            <button type="submit " class="btn btn-primary btn-block" style="background-color:#5Dbb63">Submit</button><br>
        </form>
        {{form.media}}

        </div>

    {% include 'shop/flow.html' %}
    {% include 'shop/footer.html' %}

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>